<?php
namespace App\Controller\Admin;

use App\Controller\AppController;

class AdminController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function index()
    {

    }
}