<?php
namespace App\Controller;

use App\Controller\AppController;

class OrderController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //$this->Auth->allow();

        $this->loadComponent('Cart');

        $this->loadModel('Transactions');
        $this->loadModel('Orders');
    }

    public function checkout(){
        $carts = $this->Cart->getcart();

        if(!$carts['Order']['total']) {
            $this->Flash->error(__('You have to buy products before checkout.'));
            return $this->redirect('/');
        }

        //set carts info to view
        $this->set(compact('carts'));

        $transaction = $this->Transactions->newEntity();

        if($this->request->is('post')){
            $form_data = $this->request->getData();
            $transaction_data = [
                'status'   => 0, //trạng thái chưa thanh toán
                'user_id'  => $this->Auth->user()['id'], //id thanh vien mua hang
                'user_email'    => $form_data['txtEmail'],
                'user_name'     => $form_data['txtName'],
                'user_phone'    => $form_data['txtPhone'],
                'message'       => $form_data['txtNote'], //ghi chú khi mua hàng
                'amount'        => $carts['Order']['total'],//tong so tien can thanh toan
                'payment'       => $form_data['payment'], //cổng thanh toán,
            ];

            $transaction = $this->Transactions->patchEntity($transaction, $transaction_data);

            $connection = \Cake\Datasource\ConnectionManager::get('default');

            //Start using transaction
            $result = $connection->transactional(function ($connection) use ($transaction,$carts) {
                $transaction_save = $this->Transactions->save($transaction);
                if (!$transaction_save) {
                    //$this->Flash->error(__('Error transaction_save'));
                    return false;
                }

                foreach ($carts['Orderproducts'] as $cart)
                {
                    $transaction_orders = $this->Transactions->Orders->newEntity();
                    $order_data = [
                        'transaction_id' => $transaction_save->id,
                        'product_id'     => $cart['product_id'],
                        'qty'            => $cart['quantity'],
                        'amount'         => $cart['subtotal'],
                        'status'         => '0',
                    ];
                    $transaction_orders = $this->Transactions->Orders->patchEntity($transaction_orders, $order_data);
                    $order_save = $this->Transactions->Orders->save($transaction_orders);

                    if (!$order_save) {
                        //$this->Flash->error(__('Error order_save'));
                        return false;
                    }
                }

                return true;
            });

            if($result){
                $this->Cart->clear();
                $this->Flash->success(__('Payment Success!'));
                return $this->redirect('/');
            }else{
                $this->Flash->error(__('Payment Error!'));
                return $this->redirect('/order/checkout');
            }
        }
    }
}