<?php
namespace App\Controller;

use App\Controller\AppController;
/**
 * User Controller
 *
 *
 * @method \App\Model\Entity\User[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class UserController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->Auth->allow();
        $this->loadModel('Users');

        $this->loadComponent('Cart');
    }

    public function edit(){
        $authUser = $this->Auth->user();
        $user = $this->Users->get($authUser['id'], [
                'contain' => []
            ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $data = $this->request->getData();
            if(empty($data['password'])){
                unset($data['password']);
                unset($data['password_match']);
            }
            $user = $this->Users->patchEntity($user, $data);

            if ($this->Users->save($user)) {
                $this->Flash->success(__('Edit success.'));

                return $this->redirect(['action' => 'edit']);
            }
            $this->Flash->error(__('Edit error. Please, try again.'));
        }

        $this->set(compact('user'));
    }
    public function login(){
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            $this->log($user, 'debug');
            if ($user) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            } else {
                $this->Flash->error(__('Username or password is incorrect'));
            }
        }
    }

    public function register(){
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if ($this->Users->save($user)) {
                $this->Flash->success(__('Register sucess.'));

                return $this->redirect('/');
            }
            $this->Flash->error(__('Error.'));
        }
        $this->set(compact('user'));
    }

    public function logout()
    {
        $this->Flash->success('You are now logged out.');

        //clear cart
        $this->Cart->clear();

        return $this->redirect($this->Auth->logout());
    }
}
